<?php
/** @var \AddressFinder\AddressFinder\Block\Checkout $block */
?>
<?php if ($block->isEnabled()): ?>

    <script>
        require(['magento_plugin', 'addressfinder', 'domReady!'], function (MagentoPlugin, AddressFinder) {
          var widgetConfig = <?=json_encode($block->getWidgetConfig()) ?>;

          window.AddressFinder = AddressFinder;
          new MagentoPlugin(widgetConfig);
        });
    </script>

<?php endif ?>