<?php

/** @var \AddressFinder\AddressFinder\Block\Customer $block */
?>
<?php if ($block->isEnabled()): ?>

    <script>
        require(['addressfinder_plugin', 'addressfinder', 'domReady!'], function (AddressFinderPlugin, AddressFinder) {
            var widgetConfig = {
                licenceKey: "<?=$block->getLicenceKey()?>",
                <?php if ($block->isDebugMode()): ?>
                    debugMode: true,
                <?php endif ?>
                <?php if ($block->hasWidgetOptions()): ?>
                    widgetOptions: "<?=$block->getWidgetOptionsEscaped()?>",
                <?php endif ?>
            }

            var addressFormConfig: {
                label: "Address book",
                layoutSelector: "#input#street_1",
                countryIdentifier: 'select[name=country_id]',
                searchIdentifier: "input#street_1",
                nz: {
                    countryValue: "New Zealand",
                    elements: {
                        address1: 'input#street_1',
                        suburb: 'input#street_2',
                        city: 'input[name=city]',
                        region: 'input[name=region]',
                        postcode: 'input[name=postcode]',
                    },
                regionMappings: null
                },
                au: {
                    countryValue: "Australia",
                    elements: {
                        address1: 'input#street_1',
                        address2: 'input#street_2',
                        suburb: 'input[name=city]',
                        state: 'input[name=region]',
                        postcode: 'input[name=postcode]',
                    },
                    stateMappings: null
                }
            }

            window.AddressFinder = AddressFinder;

            var PageManager = new AddressFinderPlugin.PageManager({
                addressFormConfigurations: addressFormConfig,
                widgetConfig: widgetConfig,
                eventToDispatch: 'change' 
            })
    
            window.AddressFinderPlugin._magentoPlugin = PageManager
    });
    </script>

<?php endif ?>
