<?php

/** @var \AddressFinder\AddressFinder\Block\Customer $block */
?>
<?php if ($block->isEnabled()): ?>

    <script>
        require(['addressfinder_magento', 'addressfinder', 'domReady!'], function (AddressFinderMagento, AddressFinder) {
            var widgetConfig = {
                licenceKey: "<?=$block->getLicenceKey()?>",
                <?php if ($block->isDebugMode()): ?>
                    debugMode: true,
                <?php endif ?>
                <?php if ($block->hasWidgetOptions()): ?>
                    widgetOptions: "<?=$block->getWidgetOptionsEscaped()?>",
                <?php endif ?>
            }

            window.AddressFinder = AddressFinder;

            window.AddressFinderMagento = new AddressFinderMagento()
    });
    </script>

<?php endif ?>
