<?php

/** @var \AddressFinder\AddressFinder\Block\Customer $block */
?>
<?php if ($block->isEnabled()): ?>

    <script>
        require(['magento_plugin', 'addressfinder', 'domReady!'], function (MagentoPlugin, AddressFinder) {
            var widgetConfig = {
                    key: "<?=$block->getLicenceKey()?>",
                <?php if ($block->hasWidgetOptions()): ?>
                    widgetOptions: "<?=$block->getWidgetOptionsEscaped()?>",
                <?php endif ?>
                <?php if ($block->isDebugMode()): ?>
                    debug: true,
                <?php endif ?>
            }

            window.AddressFinder = AddressFinder;
            new MagentoPlugin(widgetConfig)
    });
    </script>

<?php endif ?>