<form>
  <div class="page-main-actions">
    <div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
      <div class="page-actions-inner" data-title="AddressFinder Settings">
        <div class="page-actions-buttons">
          <button title="Save" type="button" class="action-default scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" data-ui-id="adminhtml-system-account-edit-save-button" role="button" aria-disabled="false"><span class="ui-button-text">
            <span>Save</span>
          </span></button>
        </div>
      </div>
    </div>
  </div>

  <fieldset class="fieldset admin__fieldset">
    <div class="admin__field field">
      <label for='au_licence_key' class="label admin__field-label"><span>Licence Key Australia</span></label>
      <div class='admin__field-control control'>
        <input id='au_licence_key' type='text' placeholder='AU793YPEXAMPLEKOWIN97' class=" input-text admin__control-text">
      </div>
    </div>
    <div class="admin__field field">
      <label for='nz_licence_key' class="label admin__field-label"><span>Licence Key New Zealand</span></label>
      <div class='admin__field-control control'>
        <input id='nz_licence_key' type='text' placeholder='NZ793YPEXAMPLEKOWIN97' class=" input-text admin__control-text">
      </div>
    </div>
  </fieldset>
</form>

<h3>Need a licence key?</h3>
<p>
  You need an AddressFinder account in order to use this extension.
  If you don't have one, get started with a FREE licence key for <a href='https://portal.addressfinder.io/signup/au'>Australia</a> or <a href='https://portal.addressfinder.io/signup/nz'>New Zealand</a>.
</p>
<br>
<h3>Access your account</h3>
<p>
  Track your address lookups, see debug information and manage your plan from the <a href='https://portal.addressfinder.io/sessions/login'>AddressFinder portal</a>.
</p>
