<script>
  window.debugAF = false;

  // TODO - only require addressfinder when needed
  require(['addressfinder', 'domReady!'], function(AddressFinder){
    if (debugAF){ console.debug('required addressfinder'); };

    (function() {
      var currentUrl = location.href;
      var addressFieldMappings = {
        "input#street_1": { // account address book
          street_2: "input#street_2",
          city: "input[name=city]",
          region: "input[name=region]",
          postcode: "input[name=postcode]"
        },
        ".billing-address-form input[name='street[0]']": { // billing address
          street_2: "input[name='street[1]']",
          city: "input[name=city]",
          region: "input[name=region]",
          postcode: "input[name=postcode]"
        },
        ".form-shipping-address input[name='street[0]']": { // shipping address
          street_2: "input[name='street[1]']",
          city: "input[name=city]",
          region: "input[name=region]",
          postcode: "input[name=postcode]"
        }
      }
      var addressFields = Object.keys(addressFieldMappings);
      var widgets = {};

      function usingKnockout(){
        return !!document.querySelector('[data-bind]');
      };

      function knockoutLoaded(){
        return !!document.querySelector('[data-bind]:last-child').innerText.trim().length;
      };

      function watchUrl(){
        if (debugAF){ console.debug('watching url'); };
        if (location.href != currentUrl) {
          currentUrl = location.href;
          setTimeout(initAF, 500);
        } else {
          setTimeout(watchUrl, 1000);
        }
      };

      function disableWidgets(addressGroup){
        if (debugAF){ console.debug('disabling widgets for '+addressGroup); };
        widgets[addressGroup]['AU'].disable();
        widgets[addressGroup]['NZ'].disable();
      }

      function setWidgetState(addressGroup, countrySelect){
        disableWidgets(addressGroup);
        var countryCode = countrySelect.value;
        if (countryCode && (countryCode == 'NZ' || countryCode == 'AU')) {
          if (debugAF){ console.debug('enabling '+addressGroup+" for "+countryCode); };
          widgets[addressGroup][countryCode].enable();
        };
      }

      function populateAUForm(addressGroup, metadata){
        var input = document.querySelector(addressGroup);
        input.value = metadata.address_line_1;
        input.form.querySelector(addressFieldMappings[addressGroup]['street_2']).value = metadata.address_line_2;
        input.form.querySelector(addressFieldMappings[addressGroup]['city']).value = metadata.locality_name;
        input.form.querySelector(addressFieldMappings[addressGroup]['region']).value = metadata.state_territory;
        input.form.querySelector(addressFieldMappings[addressGroup]['postcode']).value = metadata.postcode;
      };

      function populateNZForm(addressGroup, metadata){
        var wrapper = new AddressFinder.NZSelectedAddress(metadata.a, metadata);
        var input = document.querySelector(addressGroup);
        input.value = wrapper.address_line_1();
        input.form.querySelector(addressFieldMappings[addressGroup]['street_2']).value = wrapper.address_line_2() || metadata.suburb;
        input.form.querySelector(addressFieldMappings[addressGroup]['city']).value = metadata.city;
        input.form.querySelector(addressFieldMappings[addressGroup]['region']).value = metadata.region;
        input.form.querySelector(addressFieldMappings[addressGroup]['postcode']).value = metadata.postcode;
      };

      function setupWidgets(input, addressGroup){
        var au_widget = new AddressFinder.Widget(input, 'ADDRESSFINDER_AU_DEMO_KEY', 'AU', {});
        var nz_widget = new AddressFinder.Widget(input, 'ADDRESSFINDER_NZ_DEMO_KEY', 'NZ', {});
        au_widget.on("result:select", function(fullAddress, metadata){ populateAUForm(addressGroup, metadata) });
        nz_widget.on("result:select", function(fullAddress, metadata){ populateNZForm(addressGroup, metadata) });
        widgets[addressGroup] = {'AU': au_widget, 'NZ': nz_widget};
      };

      function setupCountrySwitcher(input, addressGroup){
        var countrySelect = input.form.querySelector('select[name=country_id]');
        setWidgetState(addressGroup, countrySelect);
        countrySelect.addEventListener('change', function(){
          if (debugAF){ console.debug('country changed'); };
          setWidgetState(addressGroup, countrySelect);
        });
      };

      function initAF(){
        for (var e = 0; e < addressFields.length; e++){
          var input = document.querySelector(addressFields[e]);
          if (input){
            setupWidgets(input, addressFields[e]);
            setupCountrySwitcher(input, addressFields[e]);
          };
        };

        if (!!currentUrl.match(/\/checkout/i)){ watchUrl(); };
      };

      function pageHasAddressFields(){
        return !!document.querySelectorAll(addressFields.join(', ')).length;
      };

      function loadAF(){
        if (debugAF){ console.debug('precheck'); };
        if (pageHasAddressFields()){
          // TODO - require addressfinder should go here
          initAF();
        } else {
          if (debugAF){ console.debug('there are no address fields'); };
        };
      };

      function start(){
        if (usingKnockout() && !knockoutLoaded()){
          if (debugAF){ console.debug('waiting for knockout'); };
          setTimeout(start, 2000);
        } else {
          loadAF();
        };
      };

      start();

    })();

  });
</script>