<script>
  window.debugAF = false;

  // TODO - only require addressfinder when needed
  require(['addressfinder', 'domReady!'], function(AddressFinder){
    if (debugAF){ console.debug('required addressfinder'); };

    (function() {
      var currentUrl = location.href;
      var mappings = {
        "input#street_1": { // account address book
          street_2: "input#street_2",
          city: "input[name=city]",
          region: "input[name=region]",
          postcode: "input[name=postcode]"
        },
        ".billing-address-form input[name='street[0]']": { // billing address
          street_2: "input[name='street[1]']",
          city: "input[name=city]",
          region: "input[name=region]",
          postcode: "input[name=postcode]"
        },
        ".form-shipping-address input[name='street[0]']": { // shipping address
          street_2: "input[name='street[1]']",
          city: "input[name=city]",
          region: "input[name=region]",
          postcode: "input[name=postcode]"
        }
      }
      var selectors = Object.keys(mappings);
      var widgets = {};

      function usingKnockout(){
        return !!document.querySelector('[data-bind]');
      };

      function knockoutLoaded(){
        return !!document.querySelector('[data-bind]:last-child').innerText.trim().length;
      };

      function watchUrl(){
        if (debugAF){ console.debug('watching url'); };
        if (location.href != currentUrl) {
          currentUrl = location.href;
          setTimeout(initAF, 500);
        } else {
          setTimeout(watchUrl, 1000);
        }
      };

      function disableWidgets(widgetGroup){
        if (debugAF){ console.debug('disabling widgets for '+widgetGroup); };
        widgets[widgetGroup]['AU'].disable();
        widgets[widgetGroup]['NZ'].disable();
      }

      function setWidgetState(widgetGroup, countrySelect){
        disableWidgets(widgetGroup);
        var countryCode = countrySelect.value;
        if (countryCode && (countryCode == 'NZ' || countryCode == 'AU')) {
          if (debugAF){ console.debug('enabling '+widgetGroup+" for "+countryCode); };
          widgets[widgetGroup][countryCode].enable();
        };
      }

      function populateAUForm(widgetGroup, metadata){
        var input = document.querySelector(widgetGroup);
        input.value = metadata.address_line_1;
        input.form.querySelector(mappings[widgetGroup]['street_2']).value = metadata.address_line_2;
        input.form.querySelector(mappings[widgetGroup]['city']).value = metadata.locality_name;
        input.form.querySelector(mappings[widgetGroup]['region']).value = metadata.state_territory;
        input.form.querySelector(mappings[widgetGroup]['postcode']).value = metadata.postcode;
      };

      function populateNZForm(widgetGroup, metadata){
        console.log(metadata)
        var wrapper = new AddressFinder.NZSelectedAddress(metadata.a, metadata);
        var input = document.querySelector(widgetGroup);
        input.value = wrapper.address_line_1();
        input.form.querySelector(mappings[widgetGroup]['street_2']).value = wrapper.address_line_2();
        input.form.querySelector(mappings[widgetGroup]['city']).value = metadata.city;
        input.form.querySelector(mappings[widgetGroup]['region']).value = metadata.region;
        input.form.querySelector(mappings[widgetGroup]['postcode']).value = metadata.postcode;
      };

      function initAF(){
        for (var e = 0; e < selectors.length; e++){
          (function(){
            var input = document.querySelector(selectors[e]);
            if (input){
              var widgetGroup = selectors[e];
              var au_widget = new AddressFinder.Widget(input, 'ADDRESSFINDER_AU_DEMO_KEY', 'AU', {});
              var nz_widget = new AddressFinder.Widget(input, 'ADDRESSFINDER_NZ_DEMO_KEY', 'NZ', {});
              au_widget.on("result:select", function(fullAddress, metadata){
                populateAUForm(widgetGroup, metadata)
              });
              nz_widget.on("result:select", function(fullAddress, metadata){
                populateNZForm(widgetGroup, metadata)
              });
              widgets[widgetGroup] = {'AU': au_widget, 'NZ': nz_widget};
              var countrySelect = input.form.querySelector('select[name=country_id]');
              setWidgetState(widgetGroup, countrySelect);
              countrySelect.addEventListener('change', function(){
                if (debugAF){ console.debug('country changed'); };
                setWidgetState(widgetGroup, countrySelect);
              });
            };
          })();
        };

        if (debugAF){ console.debug('DONE', widgets); };

        if (!!currentUrl.match(/\/checkout/i)){ watchUrl(); };
      };

      function loadAF(){
        if (debugAF){ console.debug('precheck'); };
        if (document.querySelectorAll(selectors.join(', ')).length){
          // TODO - require addressfinder should go here
          if (debugAF){ console.debug('addressfinder loaded', AddressFinder); };
          initAF();
        } else {
          if (debugAF){ console.debug("addressfinder isn't needed on this page"); };
        };
      };

      function start(){
        if (usingKnockout() && !knockoutLoaded()){
          if (debugAF){ console.debug('waiting for knockout'); };
          setTimeout(start, 2000);
        } else {
          loadAF();
        };
      };

      start();

    })();

  });
</script>