<?php
  $licenceKey = $block->getConfig('licence_key');
  if (!empty($licenceKey)) {
    $debugMode = $block->getConfig('debug_mode');
    $widgetOptions = $block->getConfig('widget_options');
?>

<script>
  require(['addressfinder_magento', 'addressfinder', 'domReady!'], function(AddressFinderMagento, AddressFinder){
    var options = {
      licenceKey: "<?php echo($licenceKey) ?>",
      debugMode: <?php echo($debugMode) ?>,
      widgetOptions: '<?php echo($widgetOptions) ?>',
      attachToParent: true,
      fieldMappings: {
        ".billing-address-form input[name='street[0]']": {
          addressLine2: "input[name='street[1]']",
          city: "input[name=city]",
          region: "input[name=region]",
          postcode: "input[name=postcode]",
          country: "select[name=country_id]"
        },
        ".form-shipping-address input[name='street[0]']": {
          addressLine2: "input[name='street[1]']",
          city: "input[name=city]",
          region: "input[name=region]",
          postcode: "input[name=postcode]",
          country: "select[name=country_id]"
        }
      }
    }
    window.AddressFinder = AddressFinder;
    new AddressFinderMagento.Checkout(options).start();
  });
</script>

<?php }
