<?php
  $licenceKey = $this->helper('AddressFinder\Widget\Helper\Data')->getEncryptedConfig('licence_key');
  $debugMode = $this->helper('AddressFinder\Widget\Helper\Data')->getConfig('debug_mode');
  if (!empty($licenceKey)) {
?>

<script>
  require(['addressfinder_magento', 'addressfinder', 'domReady!'], function(AddressFinderMagento, AddressFinder){
    var options = {
      licenceKey: "<?php echo($licenceKey) ?>",
      debugMode: <?php echo($debugMode) ?>,
      checkoutMode: true,
      fieldMappings: {
        ".billing-address-form input[name='street[0]']": {
          addressLine2: "input[name='street[1]']",
          city: "input[name=city]",
          region: "input[name=region]",
          postcode: "input[name=postcode]"
        },
        ".form-shipping-address input[name='street[0]']": {
          addressLine2: "input[name='street[1]']",
          city: "input[name=city]",
          region: "input[name=region]",
          postcode: "input[name=postcode]"
        }
      }
    }
    window.AddressFinder = AddressFinder;
    new AddressFinderMagento(options).start();
  });
</script>

<?php }