<?php
  $licenceKey = $this->helper('AddressFinder\Widget\Helper\Data')->getEncryptedConfig('licence_key');
  if (!empty($licenceKey)) {
    $debugMode = $this->helper('AddressFinder\Widget\Helper\Data')->getConfig('debug_mode');
    $widgetOptions = $this->helper('AddressFinder\Widget\Helper\Data')->getConfig('widget_options');
?>

<script>
  require(['addressfinder_magento', 'addressfinder', 'domReady!'], function(AddressFinderMagento, AddressFinder){
    var options = {
      licenceKey: "<?php echo($licenceKey) ?>",
      debugMode: <?php echo($debugMode) ?>,
      widgetOptions: '<?php echo($widgetOptions) ?>',
      checkoutMode: true,
      fieldMappings: [{
        pathRegex: /checkout\/#payment$/,
        addressLine1: ".billing-address-form input[name='street[0]']",
        addressLine2: "input[name='street[1]']",
        city: "input[name=city]",
        region: "input[name=region]",
        postcode: "input[name=postcode]",
        country: "select[name=country_id]"
      }, {
        addressLine1: ".form-shipping-address input[name='street[0]']",
        addressLine2: "input[name='street[1]']",
        city: "input[name=city]",
        region: "input[name=region]",
        postcode: "input[name=postcode]",
        country: "select[name=country_id]"
      }]
    }
    window.AddressFinder = AddressFinder;
    new AddressFinderMagento(options).start();
  });
</script>

<?php }