<?php
  $licenceKey = $this->helper('AddressFinder\Widget\Helper\Data')->getEncryptedConfig('licence_key');
  if (!empty($licenceKey)) {
    $debugMode = $this->helper('AddressFinder\Widget\Helper\Data')->getConfig('debug_mode');
    $widgetOptions = $this->helper('AddressFinder\Widget\Helper\Data')->getConfig('widget_options');
?>

<script>
  require(['addressfinder_magento', 'addressfinder', 'domReady!'], function(AddressFinderMagento, AddressFinder){
    var options = {
      licenceKey: "<?php echo($licenceKey) ?>",
      debugMode: <?php echo($debugMode) ?>,
      widgetOptions: '<?php echo($widgetOptions) ?>',
      fieldMappings: {
        "input#street_1": {
          addressLine2: "input#street_2",
          city: "input[name=city]",
          region: "input[name=region]",
          postcode: "input[name=postcode]",
          country: "select[name=country_id]"
        }
      }
    }
    window.AddressFinder = AddressFinder;
    new AddressFinderMagento.Page(options).start();
  });
</script>

<?php }