<?php
  $licenceKey = $this->helper('AddressFinder\Widget\Helper\Data')->getEncryptedConfig('licence_key');
  $debugMode = $this->helper('AddressFinder\Widget\Helper\Data')->getConfig('debug_mode');
  if (!empty($licenceKey)) {
?>

<script>
  require(['addressfinder_magento', 'addressfinder', 'domReady!'], function(AddressFinderMagento, AddressFinder){
    var options = {
      licenceKey: "<?php echo($licenceKey) ?>",
      debugMode: <?php echo($debugMode) ?>,
      fieldMappings: {
        "input#street_1": {
          street_2: "input#street_2",
          city: "input[name=city]",
          region: "input[name=region]",
          postcode: "input[name=postcode]"
        }
      }
    }
    window.AddressFinder = AddressFinder;
    new AddressFinderMagento(options).start();
  });
</script>

<?php }